function suicidalMonkey() {
  // Create a random number between 1 and 123456.
  var monkeysToForceIntoSuicide = Math.floor((Math.random() * 123456) + 1);
  // Add commas to the random number.
  var mTFISwithCommas = monkeysToForceIntoSuicide.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  // Change the button to that random number.
  var killornokill = Math.floor((Math.random() * 2) + 1);
  if(killornokill == 1)
  {
    document.getElementById('calculate').innerHTML = "\"Use\" " + mTFISwithCommas + " Monkeys to Calculate your Answer"
  }
  else
  {
     document.getElementById('calculate').innerHTML = "\"Kill\" " + mTFISwithCommas + " Monkeys to Calculate your Answer"
  }
}
function mathTime() {
  suicidalMonkey();
  // Create list of swear words for amazing purposes.
  var yesorNo = Math.floor((Math.random() * 2) + 1);
  if(document.getElementById('question').value == 'Song name?')
  {
    document.getElementById('yesno').innerHTML = "DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORMDARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM DARUDE - SANDSTORM";
  }
  else
  {
    if(document.getElementById('question').value == '')
    {


      document.getElementById('yesno').innerHTML = "You miserable longeared slack assed mother lover with a female genitalia for a mouth, if only you could suck my butt while licking my balls then you would be considered to be half freaking human, but then again you are only the biggest male genitalia sucker in the world with poop for brains and your fat butt is so open from being corned holed that you cannot even see your nose that is so far up the bosses butt that you need to be ejected before he takes a poop you lying no good cheating illegitimate child with poop for brains take a long flying fornicate off your ugly female dogs pockmarked face while you suck eggs through a straw.";
    }
    else
    {
      if(yesorNo == 1)
      {
        document.getElementById('yesno').innerHTML = "  YES"
      }
      else
      {
        document.getElementById('yesno').innerHTML = "  NO"
      }
    }

  }
}

